version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: metabase_db
      MYSQL_USER: metabase_user
      MYSQL_PASSWORD: metabase_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - metanet

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 3306
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_pass
      MB_DB_HOST: mysql

      # Admin hesabı otomatik oluşturulsun diye:
      MB_SETUP_ADMIN_EMAIL: admin@example.com
      MB_SETUP_ADMIN_PASSWORD: admin123
      MB_SETUP_ADMIN_NAME: MetabaseAdmin
      MB_SETUP_SITE_NAME: MyCompanyAnalytics
      MB_SETUP_SITE_LOCALE: en
      MB_EMOJI_IN_LOGS: "false"

      # Kurulum sihirbazı geçilsin:
      MB_SETUP_TOKEN: skip

    depends_on:
      - mysql
    networks:
      - metanet

volumes:
  mysql_data:

networks:
  metanet:
